drop table ORDERS;
drop table RESTATURANT;
drop table MENU;

 create table RESTATURANT(
RESTATURANT_ID int PRIMARY KEY,
RESTATURANT_NAME varchar(30)
);
create table ORDERS(
RESTATURANT_ID int,
INDEX_TYPE int, 
ORDER_ITEMS varchar(30),
KEY (RESTATURANT_ID),
CONSTRAINT FOREIGN KEY(RESTATURANT_ID) REFERENCES RESTATURANT(RESTATURANT_ID)
);
create table MENU(
RESTATURANT_ID int,
MENU_ITEMS varchar(30),
KEY (RESTATURANT_ID),
CONSTRAINT FOREIGN KEY(RESTATURANT_ID) REFERENCES RESTATURANT(RESTATURANT_ID)
);



select * from ORDERS;
select * from RESTATURANT;
select * from MENU;